import tkinter as tk

window = tk.Tk()
window.geometry("480x720")
window.title("Kalkulator Sederhana")

frame = tk.Frame(window)
frame.place(x=0, y=0, relwidth=1, relheight=1)

entry = tk.Entry(frame, width=15, font=("Arial", 35), bg="#e1e1e1")
but_equal = tk.Button(frame, text="=", width=15, height=13, bg="#e1e1e1")
but_add = tk.Button(frame, text="+", width=15, height=6, bg="#e1e1e1")
but_subtract = tk.Button(frame, text="-", width=15, height=6, bg="#e1e1e1")
but_divide = tk.Button(frame, text="/", width=15, height=6, bg="#e1e1e1")
but_multiple = tk.Button(frame, text="x", width=15, height=6, bg="#e1e1e1")
but_float = tk.Button(frame, text="00,0", width=15, height=6, bg="#e1e1e1")
but_clear = tk.Button(frame, text="C", width=15, height=6, bg="#e1e1e1")
but_backspace = tk.Button(frame, text="<--", width=15, height=6, bg="#e1e1e1")
but_empty = tk.Button(frame, text=" ", width=15, height=6, bg="#e1e1e1")
but_0 = tk.Button(frame, text="0", width=15, height=6, bg="#e1e1e1")
but_1 = tk.Button(frame, text="1", width=15, height=6, bg="#e1e1e1")
but_2 = tk.Button(frame, text="2", width=15, height=6, bg="#e1e1e1")
but_3 = tk.Button(frame, text="3", width=15, height=6, bg="#e1e1e1")
but_4 = tk.Button(frame, text="4", width=15, height=6, bg="#e1e1e1")
but_5 = tk.Button(frame, text="5", width=15, height=6, bg="#e1e1e1")
but_6 = tk.Button(frame, text="6", width=15, height=6, bg="#e1e1e1")
but_7 = tk.Button(frame, text="7", width=15, height=6, bg="#e1e1e1")
but_8 = tk.Button(frame, text="8", width=15, height=6, bg="#e1e1e1")
but_9 = tk.Button(frame, text="9", width=15, height=6, bg="#e1e1e1")


def setup_button():
    entry.place(relx=0.5, rely=0.1, anchor="center")
    but_float.place(relx=0.1, rely=0.9, anchor="center")
    but_0.place(relx=0.365, rely=0.9, anchor="center")
    but_1.place(relx=0.1, rely=0.75, anchor="center")
    but_2.place(relx=0.365, rely=0.75, anchor="center")
    but_3.place(relx=0.635, rely=0.75, anchor="center")
    but_4.place(relx=0.1, rely=0.6, anchor="center")
    but_5.place(relx=0.365, rely=0.6, anchor="center")
    but_6.place(relx=0.635, rely=0.6, anchor="center")
    but_7.place(relx=0.1, rely=0.45, anchor="center")
    but_8.place(relx=0.365, rely=0.45, anchor="center")
    but_9.place(relx=0.635, rely=0.45, anchor="center")
    but_add.place(relx=0.9, rely=0.6, anchor="center")
    but_subtract.place(relx=0.9, rely=0.45, anchor="center")
    but_divide.place(relx=0.9, rely=0.3, anchor="center")
    but_multiple.place(relx=0.635, rely=0.3, anchor="center")
    but_clear.place(relx=0.365, rely=0.3, anchor="center")
    but_backspace.place(relx=0.1, rely=0.3, anchor="center")
    but_empty.place(relx=0.635, rely=0.9, anchor="center")
    but_equal.place(relx=0.9, rely=0.825, anchor="center")

setup_button()
window.mainloop()